finalSite/finalSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('thermostat/', include('thermostat.urls'))
]

finalSite/thermostat/urls.py
from django.urls import path

from . import views

app_name = 'thermostat'
urlpatterns = [
    path('', views.index, name='index'),
    path('setTemp/', views.set_temp, name='set_temp'),
    path('setOutTime/', views.set_out_time, name='set_out_time'),
    path('updateMonitors/', views.update_monitors, name='update_monitors'),
]

finalSite/thermostat/models.py
from django.db import models

import serial

# Create your models here.

class Temperature(models.Model):
    currnt_value = models.IntegerField;
    set_value = models.IntegerField;
    unit = models.CharField(max_length=1)

    def update_temps(self):
        # ser = serial.Serial('/dev/ttyUSB0')

        # line = ser.readline().strip().lower()

        line = 'sC40r38'.lower()

        self.set_value = line[(line.index('s') + 2):line.index('r')]
        self.current_value = int(line[line.index('r') + 1:])
        self.unit = line[line.index('s') + 1:line.index('s') + 2]

finalSite/thermostat/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.conf.urls import url
from django.contrib import messages

from .models import Temperature

import serial

therm1 = Temperature()

# Create your views here.
def index(request):

    therm1.update_temps()

    if therm1.unit == 'f':
        set_temp = str(therm1.set_value) + 'ºF'
        current_temp = str(therm1.current_value) + 'ºF'
    elif therm1.unit == 'c':
        set_temp = str(therm1.set_value) + 'ºC'
        current_temp = str(therm1.current_value) + 'ºC'

    context = {
        "set_temp": set_temp,
        "current_temp": current_temp
    }
    return render(request, 'thermostat/index.html', context)
    

def set_temp(request):
    
    temp = request.POST.get('value', None)
    unit = request.POST.get('unit', None)

    if temp == '':
        messages.error(request, "No input was given")
        return redirect(reverse('thermostat:index'))

    ard_cmd = unit + temp

    '''
    Do not uncomment until deployed
    ser = serial.Serial('/dev/ttyUSB0')

    ser.write(ard_cmd)
    '''
    return redirect(reverse('thermostat:index'))

def set_out_time(request):

    start_out_time = request.POST.get('startOutTime', None)
    end_out_time = request.POST.get('endOutTime', None)
    out_temp = request.POST.get('outTemp', None)
    unit = request.POST.get('outUnit', None)

    if (start_out_time == '' or end_out_time == '') or out_temp == '':

        messages.error(request, "No input was given")

        return redirect(reverse('thermostat:index'))

    start_out_time = start_out_time[:start_out_time.index(':')] + start_out_time[start_out_time.index(':') + 1:]
    
    end_out_time = end_out_time[:end_out_time.index(':')] + end_out_time[end_out_time.index(':') + 1:]

    ard_cmd = 'o' + unit + str(out_temp) + str(start_out_time) + str(end_out_time)
    '''
    Do not uncomment until deployed
    ser = serial.Serial('/dev/ttyUSB0')

    ser.write(ard_cmd)
    '''

    return redirect(reverse('thermostat:index'))

def update_monitors(request):
    therm1.update_temps()

    if therm1.unit == 'f':
        set_temp = str(therm1.set_value) + 'ºF'
        current_temp = str(therm1.current_value) + 'ºF'
    elif therm1.unit == 'c':
        set_temp = str(therm1.set_value) + 'ºC'
        current_temp = str(therm1.current_value) + 'ºC'

    context = {
        "set_temp": set_temp,
        "current_temp": current_temp
    }
    
    test = {
        "set_temp": "50ºC",
        "current_temp": "48ºC"
    }
    
    return JsonResponse(test)

finalSite/thermostat/templates/thermostat/index.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Upstairs Thermostat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", type="text/css", href="{% static 'thermostat/styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>

<body>
    <h3>Upstairs Thermostat</h3>
    
    <hr>
    
    {% if messages %}
        <div id="errorText">
            {% for message in messages %}
                <h5>{{ message }}</h5>
            {% endfor %}
        </div>
    {% endif %}
    
    <h4 id="setTemp">Set Temp : {{ set_temp }}</h4>
        
    <h4 id="currentTemp">Current Temp : {{ current_temp }}</h4>

    <br>
    <br>

    <form action="{% url 'thermostat:set_temp' %}" method=post>
        {% csrf_token %}
        
        <label>Input Temperature : </label>
        <input type="number" name="value" placeholder="number">
        <select name="unit">
            <option value="F">F</option>
            <option value="C">C</option>
        </select>
        <button type="submit" name="submit" value="enter">enter</button>
    </form>

    <br>
    <br>

    <form action="{% url 'thermostat:set_out_time' %}" method=post>
        {% csrf_token %}

        <label>Input Out Time</label>
        <input type="time" name="startOutTime" placeholder="start time (hh:mm)">
        <input type="time" name="endOutTime" placeholder="end time (hh:mm)">
        <input type="number" name="outTemp" placeholder="out temperature">
        <select name="outUnit">
            <option value="F">F</option>
            <option value="C">C</option>
        </select>
        <button type="submit" name="submit" value="enter">enter</button>
    </form>

    <script>

        setInterval(function() {
            $.getJSON("updateMonitors/", function(data) {
                $("#setTemp").html(`Set Temp : ${data.set_temp}`);
                $("#currentTemp").html(`Current Temp : ${data.current_temp}`);
                console.log(data);
            });
        }, 
        5000);
    </script>

</body>

finalSite/thermostat/templates/thermostat/updateMonitors.html
<h4>{{ set_temp }}</h4>